from pydantic import BaseModel
from typing import Optional

# -------------------- BASE --------------------
class UnitBase(BaseModel):
    id: Optional[int] = None  
    name: str

# -------------------- CREATE --------------------
class UnitCreate(UnitBase):
    pass
    # Inherits name and floor from UnitBase
    # id is not included here because it will be auto-generated by DB

# -------------------- UPDATE --------------------
class UnitUpdate(BaseModel):
    id: int  # id is required to identify which unit to update
    name: Optional[str] = None
    # All fields are optional for partial updates

# -------------------- RESPONSE --------------------
class UnitResponse(UnitBase):
    id: int  # id is required in response

    class Config:
        orm_mode = True
        # Allows SQLAlchemy models to be returned directly in FastAPI responses
